package com.commercetools.pspadapter.facade;

import java.util.function.Function;
import java.util.function.Supplier;

import static org.assertj.core.api.Assertions.assertThat;

public class CacheableConfigTestUtil {

    /**
     * Assert that:<ul>
     * <li>{@code cacheableFactoryMethod}:<ul>
     * <li>produces the same {@code VALUE} instances if called twice with the same {@code CONFIG} instance</li>
     * <li>produces the same {@code VALUE} instances if called with other but equal {@code CONFIG} instance</li>
     * </ul>
     * <li>also, we expect the instances generated by {@code sameConfigSupplier} are not the same reference,
     * but equal to each other (in term of {@link Object#equals(Object)}),
     * when {@code differentConfigSupplier} produces not equal {@link CONFIG}</li>
     * </li>
     * </ul>
     *
     * @param factoryInstance         factory instance, just to ensure it is not null
     * @param sameConfigSupplier      config generator. Sequential call of this method should produce different references,
     *                                but actual instances should be equal (in meaning of
     *                                <code>{@link Object#equals(Object)} == true</code>)
     * @param differentConfigSupplier config generator which produces instance not equal to values from
     *                                {@code sameConfigSupplier}
     * @param cacheableFactoryMethod  method which should produce the same instances, if passed equal configs.
     * @param <FACTORY>               factory function to test, which when accepts equal {@code CONFIG}s produces the
     *                                same {@code VALUE} instances
     * @param <CONFIG>                type of config based on which {@code cacheableFactoryMethod} method produces {@code VALUE}
     * @param <VALUE>                 type of value produced by {@code cacheableFactoryMethod} method.
     */
    public static <FACTORY, CONFIG, VALUE> void assertFactoryMethodCaching(
            FACTORY factoryInstance,
            Supplier<CONFIG> sameConfigSupplier,
            Supplier<CONFIG> differentConfigSupplier,
            Function<CONFIG, VALUE> cacheableFactoryMethod) {

        assertThat(factoryInstance).isNotNull();

        // different instances of the same config
        CONFIG config1 = sameConfigSupplier.get();
        CONFIG config3 = sameConfigSupplier.get();
        CONFIG configDifferent = differentConfigSupplier.get();

        // but they are expected to be equal
        assertThat(config1).isNotSameAs(config3);
        assertThat(config1).isEqualTo(config3);

        assertThat(config1.hashCode()).isEqualTo(config3.hashCode());
        assertThat(configDifferent).isNotEqualTo(config1);
        assertThat(configDifferent).isNotEqualTo(config3);

        // value1 and value2 created from the same instance, client3 - from different but equal instance,
        // but all fetched from factory methods should be the same instance
        VALUE value1 = cacheableFactoryMethod.apply(config1);
        VALUE value2 = cacheableFactoryMethod.apply(config1);
        VALUE value3 = cacheableFactoryMethod.apply(config3);
        VALUE valueDifferent = cacheableFactoryMethod.apply(configDifferent);

        assertThat(value1).isNotNull();
        assertThat(value1).isSameAs(value2);
        assertThat(value1).isSameAs(value3);
        assertThat(valueDifferent).isNotEqualTo(value1);
        assertThat(valueDifferent).isNotEqualTo(value2);
        assertThat(valueDifferent).isNotEqualTo(value3);
    }

}