FROM java:openjdk-8-jre

MAINTAINER DevOps <ops@commercetools.de>

COPY build/libs/commercetools-paypalplus-integration-java.jar /build/commercetools-paypalplus-integration-java.jar

CMD ["java", "-jar", "/build/commercetools-paypalplus-integration-java.jar"]

EXPOSE 8080
